const logicTypes = {
	HANDLE_KEYPRESS: 'KEYPRESS',
	SET_IS_LOCKED: 'SET_IS_LOCKED',
	SET_BOX_CODE: 'SET_BOX_CODE',
	RESET_INPUT_SEQUENCE: 'RESET_INPUT_SEQUENCE',
	SET_SERVICE_MODE: 'SET_SERVICE_MODE',
	SET_CONFIRM: 'SET_CONFIRM',
};

export default logicTypes;